### ISSUE TITLE
How to make charnames and charnames_fixed?

### ISSUE THREAD

**Issue by nkrapivin** [Slynchy/March22-Lua#1]
I can't understand.

**Comment by Slynchy** [comment]
Hi!

I think I reused the same stylings from my RPY-eBook project. You can find an example on how to setup those files here: https://github.com/Slynchy/RPY-eBook/tree/master/samples/katawa_shoujo/shizune_txt

Hope that helps!

**Comment by nkrapivin** [comment]
I think you didn't understand my question (sry for bad english if it is)
I am trying to port DDLC (yes)
so here what i've done
charnames:
narrator
mc
s
m
n
y
ny
charnames_fixed:
Sayori
Monika
Natsuki
Yuri
???
Girl 3
Girl 2
Girl 1
Nat & Yuri
So, after parsing every script is just a bunch of
```
ACTIVE_SCRIPT = {
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end )
};
```

**Comment by nkrapivin** [comment]
Using RenPSP is hard because of old defines and every jpg needs to be resized. (because of PSP resolution)

**Comment by nkrapivin** [comment]
Maybe there is some charnames,txt creator?

**Comment by Slynchy** [comment]
Well because the charnames(fixed) files are fairly simple, I didn't make a tool for that. But your syntax seems correct so it should be working... Can you attach an RPY file you're trying to convert and I'll take a look.

**Comment by nkrapivin** [comment]
sure. idk what file sharing service you like so I uploaded it to transfer.sh

https://transfer.sh/2sj0p/ddlc-1.1.1-decompiled-scripts.zip

also here is scriptfiles.txt (was pretty easy to make "find -name "*.rpy"")
./scripts/game_cgs.rpy
./scripts/game_console.rpy
./scripts/game_credits.rpy
./scripts/game_definitions.rpy
./scripts/game_effects.rpy
./scripts/game_glitchtext.rpy
./scripts/game_gui.rpy
./scripts/game_options.rpy
./scripts/game_poems.rpy
./scripts/game_poems_special.rpy
./scripts/game_screens.rpy
./scripts/game_script-ch0.rpy
./scripts/game_script-ch1.rpy
./scripts/game_script-ch10.rpy
./scripts/game_script-ch2.rpy
./scripts/game_script-ch20.rpy
./scripts/game_script-ch21.rpy
./scripts/game_script-ch22.rpy
./scripts/game_script-ch23.rpy
./scripts/game_script-ch3.rpy
./scripts/game_script-ch30.rpy
./scripts/game_script-ch4.rpy
./scripts/game_script-ch40.rpy
./scripts/game_script-ch5.rpy
./scripts/game_script-exclusives-natsuki.rpy
./scripts/game_script-exclusives-sayori.rpy
./scripts/game_script-exclusives-yuri.rpy
./scripts/game_script-exclusives2-natsuki.rpy
./scripts/game_script-exclusives2-yuri.rpy
./scripts/game_script-poemgame.rpy
./scripts/game_script-poemresponses.rpy
./scripts/game_script-poemresponses2.rpy
./scripts/game_script.rpy
./scripts/game_splash.rpy
./scripts/game_transforms.rpy
./scripts/renpy_common_000atl.rpy
./scripts/renpy_common_000namespaces.rpy
./scripts/renpy_common_000statements.rpy
./scripts/renpy_common_000window.rpy

**Comment by Slynchy** [comment]
Ok, so firstly your charnames files are not formatted correctly. It should be that the fixed file has the fixed charname on the same line. So for example:

Charnames:
`sl`
`m22`

Charnames fixed:
`Sam Lynch`
`March22`

And I figured out what was wrong with RPYtoLua. Turns out I don't trim the input strings, so the file being indented is what breaks it. If you just CTRL-A (select all) in the script file and SHIFT-TAB until all lines are at the left, then the algorithm works fine:

`Line.new("Sayori", March22.WHITE_COLOUR, "\"Heeeeeeeyyy!!\""),`
	`Line.new("", March22.WHITE_COLOUR, "I see an annoying girl running toward me from the distance, waving her arms in the air like she's totally oblivious to any attention she might draw to herself."),`
	`Line.new("", March22.WHITE_COLOUR, "That girl is Sayori, my neighbor and good friend since we were children."),`
	`Line.new("", March22.WHITE_COLOUR, "You know, the kind of friend you'd never see yourself making today, but it just kind of works out because you've known each other for so long?"),`
	`Line.new("", March22.WHITE_COLOUR, "We used to walk to school together on days like this, but starting around high school she would oversleep more and more frequently, and I would get tired of waiting up."),`
	`Line.new("", March22.WHITE_COLOUR, "But if she's going to chase after me like this, I almost feel better off running away."),`
	`Line.new("", March22.WHITE_COLOUR, "However, I just sigh and idle in front of the crosswalk and let Sayori catch up to me."),`
	`Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),`
	`Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),`

**Comment by nkrapivin** [comment]
s - sayori
m - monika
n - natsuki
y - yuri
ny - nat & yuri
narrator - ?!?!?!?!?!?!? maybe player???
and what about Girl 1 Girl 2 and Girl 3, and "???"

**Comment by nkrapivin** [comment]
charnames:
playername
s
m
n
y
ny
ch4
charnames_fixed:
"" blank bcuz should be set in-game menu
Sayori
Monika
Natsuki
Yuri
Nat & Yuri
Yuri
still the same result
```-- This file was automatically generated by RPYtoLua v0.6.6
-- For use with March22-Lua
-- By Sam Lynch

dofile("app0:/LUA_CLASSES/Line.lua");
dofile("app0:/March22_background.lua");


LOADEDSFX = {};
LOADEDMUSIC = {};
LABEL_POSITIONS = {};
March22.CURRENTSCRIPTNAME = "game_script-ch0.lua";

LABEL_POSITIONS["_main"] = 1;
LABEL_POSITIONS["_kill"] = 575;



ACTIVE_SCRIPT = {
	Line.new("", March22.WHITE_COLOUR, "", function() --[[ _main ]] end),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.NextLine(); end ),```

**Comment by nkrapivin** [comment]
i have opened every script in notepad++, pressed shift-tab, then closed.

**Comment by Slynchy** [comment]
I wish I could help you further but I'm at the airport right now to go on vacation for two weeks. Your charnames files are still not formatted correctly though, but you should still see output, so I can only assume you haven't removed the indentations properly. Again, try to make it so all lines in the script file are as far to the left as possible.

**Comment by nkrapivin** [comment]
maybe remove TAB-ulation at all?
allign all strings to the left? could that work?

**Comment by Slynchy** [comment]
I've made a patch to remove the whitespace to RPYtoLua but I do not have access to a compiler at the moment (at airport again!). Can you confirm if you are still having issues?

**Comment by nkrapivin** [comment]
Where?

**Comment by Slynchy** [comment]
Did you manage to figure out how to shift-tab all the lines of script so RPYtoLua works? Because I was able to do it without issues, so I'm not keen on getting a compiler to update the app to fix it since it does already (kinda) work.
