### ISSUE TITLE
Don’t understand how to compile to VPK.

### ISSUE THREAD

**Issue by noctisatrae** [Slynchy/March22-Lua#2]
Hello 👋 ! Your project is awesome. I’d like to create a VN for PS Vita and your project is the only to allow me to create my game.

But I don’t understand how to use it. How do I compile it to VPK ?
Thanks.

**Comment by Slynchy** [comment]
Hey! Thanks for your interest. My honest suggestion is to find the Katawa Shoujo demo VPK, unzip it (`.vpk` files are just zip files), and mod the files in there.

But, if you want to dev from scratch, the documentation is quite bad, so I'll try my best to explain here (although it has been 4 years!)

- Download lpp-vita and get familiar with getting a "hello world" to show from Lua on your PS Vita. 
- You can find a release that should work with March22 here: https://github.com/Rinnegatamante/lpp-vita/releases/tag/r6 

This is most of the work in answering your question, but once that's done, you want to convert your RPY script to Lua (I assume):

- Download the [RPYtoLua](https://github.com/Slynchy/March22-Lua/releases/tag/0.6.6) binaries and extract somewhere
- Follow the readme file inside the `.rar` file
- **NOTE: Your `.rpy` files cannot have indentation. All lines of code must start on the left.** (never got around to fixing this bug)
- You should have an `imachine.lua` file, and any other script files you converted to `.lua`

Once you have your script files:

- Clone the Visual Novel branch of March22-Lua (it's the only other branch)
- Copy all the `.lua` files, and the `scripts` and `graphics` folders, into where your lpp-vita folder is (wherever your `index.lua` file for "hello world" is; overwrite anything)
- Copy your RPYtoLua output files into the `scripts` folder (also overwriting anything here)

**Comment by noctisatrae** [comment]
Thanks 😊 ! 
Did you know that I found this — it might be helpful -> [LPP-BuildVita](http://gs2012.xyz/PC/lppbuildervita/).

It allows you to compile your Lua project in `.vpk`. Just got to build my Ren’py project, build it with your tool and use the tool linked above.

I’m very impressed by your work, I’d like to contribute to PS Vita Homebrew scene. But I don’t know C++ and all that stuff ; my favorite langage is Typescript and Svelte. 

After all, I’m only 14 years old but I really wish to help… I don’t think that is a problem. 
(I’m French, so my English won’t be perfect)

**Comment by Slynchy** [comment]
Yes, that LPP-BuildVita app looks like it makes the VPK building process in lpp-vita nice and easy, good find.

And keep at it, mate; I started coding at your age and it really, really helped for going professional later. And hell, I didn't even learn another language until last year, so being even somewhat bilingual is a massive advantage.
